name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 
      run: |
        yarn install
        yarn build
        yarn test
        cd example
        yarn install
        yarn build
